// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/angelokurtis/go-talk/internal/openai"
	"github.com/angelokurtis/go-talk/pkg/demo"
)

// Injectors from wire_inj.go:

func NewManager() (*Manager, func(), error) {
	config, err := openai.NewConfig()
	if err != nil {
		return nil, nil, err
	}

	client, err := openai.NewClient(config)
	if err != nil {
		return nil, nil, err
	}

	speechGenerator := demo.NewSpeechGenerator(client)
	mp3Writer := demo.NewMP3Writer()
	manager := &Manager{
		SpeechGenerator: speechGenerator,
		MP3Writer:       mp3Writer,
	}

	return manager, func() {
	}, nil
}
