// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/angelokurtis/go-talk/pkg/demo"
	"net/http"
)

// Injectors from wire_inj.go:

func NewManager() (*Manager, func(), error) {
	client := &http.Client{}
	elevenLabsAPI := demo.NewElevenLabs(client)
	manager := &Manager{
		ElevenLabsAPI: elevenLabsAPI,
	}

	return manager, func() {
	}, nil
}
